[package]
name = "dsync-shared"
version = "0.1.0"
edition = "2024"

[dependencies]
dsync-proto = { path = "../dsync-proto" }
thiserror = { workspace = true }
anyhow = { workspace = true }
tonic = { workspace = true }
